service: testService

frameworkVersion: '3'

plugins:
  - ../index.js

provider:
  name: aws
  runtime: nodejs12.x
  logRetentionInDays: 7
  tracing:
    lambda: true
    apiGateway: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  lambdaOTEL: 
    enable: true
